services:

  rabbitmq:
    volumes:
      - "./rabbitmq/rabbitmq-init.sh:/setup/rabbitmq-init.sh"
    environment:
      RABBITMQ_OMOTES_USER_NAME: ${RABBITMQ_OMOTES_USER_NAME}
      RABBITMQ_OMOTES_USER_PASSWORD: ${RABBITMQ_OMOTES_USER_PASSWORD}
      RABBITMQ_CELERY_USER_NAME: ${RABBITMQ_CELERY_USER_NAME}
      RABBITMQ_CELERY_USER_PASSWORD: ${RABBITMQ_CELERY_USER_PASSWORD}

  omotes_influxdb:
    volumes:
      - "./influxdb/influxdb-init.sh:/setup/influxdb-init.sh"
    environment:
      INFLUXDB_WRITE_USER: ${INFLUXDB_WRITE_USER}
      INFLUXDB_WRITE_USER_PASSWORD: ${INFLUXDB_WRITE_USER_PASSWORD}
      INFLUXDB_FRONTEND_ADMIN_USER: ${INFLUXDB_FRONTEND_ADMIN_USER}
      INFLUXDB_FRONTEND_ADMIN_USER_PASSWORD: ${INFLUXDB_FRONTEND_ADMIN_USER_PASSWORD}
      INFLUXDB_PORT: ${INFLUXDB_PORT}

  orchestrator_postgres_db:
    volumes:
      - "./postgres/postgres-init.sql:/setup/init.sql"

