version: "3.8"

networks:
    nwn:

volumes:
  db-data:
  broker-data:

services:
    rabbitmq:
        image: rabbitmq:3.12-management
        restart: unless-stopped
        volumes:
            - "broker-data:/var/lib/rabbitmq/"
        environment:
            - RABBITMQ_DEFAULT_USER=${RABBITMQ_ROOT_USER}
            - RABBITMQ_DEFAULT_PASS=${RABBITMQ_ROOT_PASSWORD}
        hostname: rabbitmq-nwn
        ports:
            - '5672:5672'
            - '15672:15672'
        networks:
            - nwn
        healthcheck:
            test: rabbitmq-diagnostics -q ping
            interval: 10s
            timeout: 5s
            retries: 10

    postgres_db:
        image: postgres:15.4
        restart: unless-stopped
        volumes:
            - "db-data:/var/lib/postgresql/data/"
        ports:
            - "${POSTGRES_PORT:-5432}:5432"
        networks:
            - nwn
        environment:
            PGDATA: /var/lib/postgresql/data
            POSTGRES_DB: ${POSTGRES_DATABASE_NAME}
            POSTGRES_USER: ${POSTGRES_ROOT_USER}
            POSTGRES_PASSWORD: ${POSTGRES_ROOT_PASSWORD}
        healthcheck:
            test: ["CMD", "pg_isready", "-U", "${POSTGRES_ROOT_USER}", "-d", "${POSTGRES_DATABASE_NAME}"]
            interval: 5s
            timeout: 5s
            retries: 10

    # Skipped in 'docker-compose up', only used in 'postgres_upgrade.sh'
    postgres_db_upgrade:
        build: ./
        networks:
            - nwn
        environment:
            POSTGRES_HOST: postgres_db
            POSTGRES_ROOT_USER: ${POSTGRES_ROOT_USER}
            POSTGRES_ROOT_PASSWORD: ${POSTGRES_ROOT_PASSWORD}
            POSTGRES_PORT: 5432
            POSTGRES_DATABASE_NAME: ${POSTGRES_DATABASE_NAME}
        depends_on:
            postgres_db:
                condition: service_healthy
        profiles:
            - postgres-upgrade

    optimization_worker:
        image: tnoslafleur/nwn_optimization_worker:0.0.7
        restart: unless-stopped
        deploy:
            replicas: 2
        networks:
            - nwn
        environment:
            POSTGRES_HOST: postgres_db
            POSTGRES_ROOT_USER: ${POSTGRES_ROOT_USER}
            POSTGRES_ROOT_PASSWORD: ${POSTGRES_ROOT_PASSWORD}
            POSTGRES_PORT: 5432
            POSTGRES_DATABASE_NAME: ${POSTGRES_DATABASE_NAME}
            RABBITMQ_HOST: rabbitmq-nwn
            RABBITMQ_PORT: 5672
            RABBITMQ_ROOT_USER: ${RABBITMQ_ROOT_USER}
            RABBITMQ_ROOT_PASSWORD: ${RABBITMQ_ROOT_PASSWORD}
            RABBITMQ_HIPE_COMPILE: ${RABBITMQ_HIPE_COMPILE}
            RABBITMQ_EXCHANGE: ${RABBITMQ_EXCHANGE}
        depends_on:
            postgres_db:
                condition: service_healthy
            rabbitmq:
                condition: service_healthy

    mapeditor-nwn-dispatcher:
        image: mvrijlandt/mapeditor_nwn_dispatcher:0.0.3-post1
        ports:
            - "9200:9200"
        networks:
            - nwn
        environment:
            NWN_POSTGRES_HOST: postgres_db
            NWN_POSTGRES_ROOT_USER: ${POSTGRES_ROOT_USER}
            NWN_POSTGRES_ROOT_PASSWORD: ${POSTGRES_ROOT_PASSWORD}
            NWN_POSTGRES_PORT: 5432
            NWN_POSTGRES_DATABASE_NAME: ${POSTGRES_DATABASE_NAME}
            NWN_RABBITMQ_HOST: rabbitmq-nwn
            NWN_RABBITMQ_PORT: 5672
            NWN_RABBITMQ_ROOT_USER: ${RABBITMQ_ROOT_USER}
            NWN_RABBITMQ_ROOT_PASSWORD: ${RABBITMQ_ROOT_PASSWORD}
            NWN_RABBITMQ_HIPE_COMPILE: ${RABBITMQ_HIPE_COMPILE}
            NWN_RABBITMQ_EXCHANGE: ${RABBITMQ_EXCHANGE}
        depends_on:
            postgres_db:
                condition: service_healthy
            rabbitmq:
                condition: service_healthy
        profiles:
            - mapeditor-dispatcher
