version: "3.8"

networks:
    nwn:

volumes:
  db-data:
  broker-data:
  influxdb_storage:

services:
    rabbitmq:
        image: rabbitmq:3.12-management
        restart: unless-stopped
        volumes:
            - "broker-data:/var/lib/rabbitmq/"
            - "./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf"
        environment:
            - RABBITMQ_DEFAULT_USER=${RABBITMQ_ROOT_USER}
            - RABBITMQ_DEFAULT_PASS=${RABBITMQ_ROOT_PASSWORD}
        hostname: rabbitmq-nwn
        ports:
            - '5672:5672'
            - '15672:15672'
        networks:
            - nwn
        healthcheck:
            test: rabbitmq-diagnostics -q ping
            interval: 10s
            timeout: 5s
            retries: 10

    omotes_influxdb:
        image: influxdb:1.7
        ports:
            - "${INFLUXDB_PORT}:${INFLUXDB_PORT}"
            - "${INFLUXDB_RPC_PORT}:${INFLUXDB_RPC_PORT}"
        networks:
            - nwn
        environment:
            - INFLUXDB_ADMIN_USER=${INFLUXDB_ADMIN_USER}
            - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_ADMIN_PASSWORD}
            - INFLUXDB_HTTP_BIND_ADDRESS=:${INFLUXDB_PORT}
            - INFLUXDB_BIND_ADDRESS=:${INFLUXDB_RPC_PORT}
            - INFLUXDB_DB=omotes_timeseries
            - INFLUXDB_WRITE_USER=${INFLUXDB_WRITE_USER}
            - INFLUXDB_WRITE_USER_PASSWORD=${INFLUXDB_WRITE_USER_PASSWORD}
        healthcheck:
            test: [ "CMD", "curl", "-f", "http://omotes_influxdb:${INFLUXDB_PORT}/ping" ]
            interval: 10s
            timeout: 5s
        volumes:
            - influxdb_storage:/var/lib/influxdb

    orchestrator:
        image: ghcr.io/project-omotes/omotes_orchestrator:0.0.4
        restart: unless-stopped
        networks:
            - nwn
        environment:
            CELERY_RABBITMQ_USERNAME: ${RABBITMQ_CELERY_USER_NAME}
            CELERY_RABBITMQ_PASSWORD: ${RABBITMQ_CELERY_USER_PASSWORD}
            CELERY_RABBITMQ_HOSTNAME: rabbitmq-nwn
            CELERY_RABBITMQ_PORT: 5672
            CELERY_RABBITMQ_VIRTUALHOST: omotes_celery

            SDK_RABBITMQ_USERNAME: ${RABBITMQ_OMOTES_USER_NAME}
            SDK_RABBITMQ_PASSWORD: ${RABBITMQ_OMOTES_USER_PASSWORD}
            SDK_RABBITMQ_HOSTNAME: rabbitmq-nwn
            SDK_RABBITMQ_PORT: 5672
            SDK_RABBITMQ_VIRTUALHOST: omotes

            TASK_RABBITMQ_USERNAME: ${RABBITMQ_CELERY_USER_NAME}
            TASK_RABBITMQ_PASSWORD: ${RABBITMQ_CELERY_USER_PASSWORD}
            TASK_RABBITMQ_HOSTNAME: rabbitmq-nwn
            TASK_RABBITMQ_PORT: 5672
            TASK_RABBITMQ_VIRTUALHOST: omotes_celery
        depends_on:
            rabbitmq:
                condition: service_healthy

    grow_worker_optimizer:
        image: ghcr.io/project-omotes/omotes-grow-optimizer-worker:1.0.3
        restart: unless-stopped
        deploy:
            replicas: 2
        networks:
            - nwn
        environment:
            INFLUXDB_HOSTNAME: omotes_influxdb
            INFLUXDB_PORT: ${INFLUXDB_PORT}
            INFLUXDB_USERNAME: ${INFLUXDB_ADMIN_USER}
            INFLUXDB_PASSWORD: ${INFLUXDB_ADMIN_PASSWORD}

            RABBITMQ_HOSTNAME: rabbitmq-nwn
            RABBITMQ_PORT: 5672
            RABBITMQ_USERNAME: ${RABBITMQ_CELERY_USER_NAME}
            RABBITMQ_PASSWORD: ${RABBITMQ_CELERY_USER_PASSWORD}
            RABBITMQ_VIRTUALHOST: omotes_celery

            GROW_TASK_TYPE: grow_optimizer
            LOG_LEVEL: INFO
        depends_on:
            rabbitmq:
                condition: service_healthy

    grow_worker_simulator:
        image: ghcr.io/project-omotes/omotes-grow-optimizer-worker:1.0.3
        restart: unless-stopped
        deploy:
            replicas: 2
        networks:
            - nwn
        environment:
            INFLUXDB_HOSTNAME: omotes_influxdb
            INFLUXDB_PORT: ${INFLUXDB_PORT}
            INFLUXDB_USERNAME: ${INFLUXDB_ADMIN_USER}
            INFLUXDB_PASSWORD: ${INFLUXDB_ADMIN_PASSWORD}

            RABBITMQ_HOSTNAME: rabbitmq-nwn
            RABBITMQ_PORT: 5672
            RABBITMQ_USERNAME: ${RABBITMQ_CELERY_USER_NAME}
            RABBITMQ_PASSWORD: ${RABBITMQ_CELERY_USER_PASSWORD}
            RABBITMQ_VIRTUALHOST: omotes_celery

            GROW_TASK_TYPE: grow_simulator
            LOG_LEVEL: INFO
        depends_on:
            rabbitmq:
                condition: service_healthy

#    mapeditor-nwn-dispatcher:
#        image: mvrijlandt/mapeditor_nwn_dispatcher:0.0.7
#        ports:
#            - "9200:9200"
#        networks:
#            - nwn
#        environment:
#            NWN_POSTGRES_HOST: postgres_db
#            NWN_POSTGRES_ROOT_USER: ${POSTGRES_ROOT_USER}
#            NWN_POSTGRES_ROOT_PASSWORD: ${POSTGRES_ROOT_PASSWORD}
#            NWN_POSTGRES_PORT: 5432
#            NWN_POSTGRES_DATABASE_NAME: ${POSTGRES_DATABASE_NAME}
#            NWN_RABBITMQ_HOST: rabbitmq-nwn
#            NWN_RABBITMQ_PORT: 5672
#            NWN_RABBITMQ_ROOT_USER: ${RABBITMQ_ROOT_USER}
#            NWN_RABBITMQ_ROOT_PASSWORD: ${RABBITMQ_ROOT_PASSWORD}
#            NWN_RABBITMQ_HIPE_COMPILE: ${RABBITMQ_HIPE_COMPILE}
#            NWN_RABBITMQ_EXCHANGE: ${RABBITMQ_EXCHANGE}
#        depends_on:
#            postgres_db:
#                condition: service_healthy
#            rabbitmq:
#                condition: service_healthy
#        profiles:
#            - mapeditor-dispatcher
