apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ./kompose -f docker-compose.yml convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: grow-worker-optimizer-no-heat-losses
  name: grow-worker-optimizer-no-heat-losses
spec:
  replicas: 2
  selector:
    matchLabels:
      io.kompose.service: grow-worker-optimizer-no-heat-losses
  template:
    metadata:
      annotations:
        kompose.cmd: ./kompose -f docker-compose.yml convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: grow-worker-optimizer-no-heat-losses
    spec:
      containers:
        - env:
            - name: GROW_TASK_TYPE
              value: grow_optimizer_no_heat_losses
            - name: INFLUXDB_HOSTNAME
              value: omotes_influxdb
            - name: INFLUXDB_PASSWORD
            - name: INFLUXDB_PORT
            - name: INFLUXDB_USERNAME
            - name: LOG_LEVEL
            - name: RABBITMQ_HOSTNAME
              value: rabbitmq-nwn
            - name: RABBITMQ_PASSWORD
            - name: RABBITMQ_PORT
              value: "5672"
            - name: RABBITMQ_USERNAME
            - name: RABBITMQ_VIRTUALHOST
              value: omotes_celery
          image: ghcr.io/project-omotes/omotes-grow-optimizer-worker:2.0.1
          name: grow-worker-optimizer-no-heat-losses
      restartPolicy: Always
