apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ./kompose -f docker-compose.yml convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: omotes-influxdb
  name: omotes-influxdb
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: omotes-influxdb
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: ./kompose -f docker-compose.yml convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: omotes-influxdb
    spec:
      containers:
        - env:
            - name: INFLUXDB_ADMIN_PASSWORD
            - name: INFLUXDB_ADMIN_USER
            - name: INFLUXDB_BIND_ADDRESS
              value: ':'
            - name: INFLUXDB_DB
              value: omotes_timeseries
            - name: INFLUXDB_HTTP_AUTH_ENABLED
              value: "true"
            - name: INFLUXDB_HTTP_BIND_ADDRESS
              value: ':'
            - name: LOG_LEVEL
          image: influxdb:1.7
          livenessProbe:
            exec:
              command:
                - curl
                - -f
                - http://omotes_influxdb:/ping
            periodSeconds: 10
            timeoutSeconds: 5
          name: omotes-influxdb
          ports:
            - containerPort: 8096
              protocol: TCP
            - containerPort: 8098
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/influxdb
              name: influxdb-storage
      restartPolicy: Always
      volumes:
        - name: influxdb-storage
          persistentVolumeClaim:
            claimName: influxdb-storage
