apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ./kompose -f docker-compose.yml convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: orchestrator-postgres-db
  name: orchestrator-postgres-db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: orchestrator-postgres-db
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: ./kompose -f docker-compose.yml convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: orchestrator-postgres-db
    spec:
      containers:
        - env:
            - name: LOG_LEVEL
            - name: PGDATA
              value: /var/lib/postgresql/data
            - name: POSTGRES_DB
              value: omotes_jobs
            - name: POSTGRES_PASSWORD
            - name: POSTGRES_USER
          image: postgres:15.4
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - ""
                - -d
                - omotes_jobs
            failureThreshold: 10
            periodSeconds: 5
            timeoutSeconds: 5
          name: orchestrator-postgres-db
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: db-data
      restartPolicy: Always
      volumes:
        - name: db-data
          persistentVolumeClaim:
            claimName: db-data
