name: Build-Test-Lint-etc (linux)

on: [push]

jobs:
  test_system:
    name: Run system tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.11" ]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
    - name: run system tests
      run: |
        cp .env-template .env
        ./scripts/test_system.sh
